/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.alipay.sofa.registry.common.model.client.pb; // Generated by the protocol buffer
                                                         // compiler.  DO NOT EDIT!
// source: PublisherRegisterService.proto

public final class PublisherRegisterServiceOuterClass {
  private PublisherRegisterServiceOuterClass() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    String[] descriptorData = {
      "\n\036PublisherRegisterService.proto\032\031Publis"
          + "herRegisterPb.proto\032\030RegisterResponsePb."
          + "proto2R\n\030PublisherRegisterService\0226\n\007req"
          + "uest\022\024.PublisherRegisterPb\032\023.RegisterRes"
          + "ponsePb\"\0002`\n\032BiPublisherRegisterService\022"
          + "B\n\017requestBiStream\022\024.PublisherRegisterPb"
          + "\032\023.RegisterResponsePb\"\000(\0010\001B\005P\001\210\001\001b\006prot"
          + "o3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              PublisherRegisterPbOuterClass.getDescriptor(),
              RegisterResponsePbOuterClass.getDescriptor(),
            });
    PublisherRegisterPbOuterClass.getDescriptor();
    RegisterResponsePbOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
